function parsave_sim_2D(FILENAME, model, params, species, mconc, conc, targ, AC_basal_sim, AC_dip_sim, AC_t_sim, AC_basal_th, AC_dip_th, AC_t_th)
		save(FILENAME,'model','params','species',...
			'mconc','conc','targ', ...
			'AC_basal_sim','AC_dip_sim','AC_t_sim',...
			'AC_basal_th', 'AC_dip_th', 'AC_t_th');
end
